[package]
name = "acrn-configurator"
version = "0.1.0"
description = "ACRN Configurator"
authors = ["Feng, Weiyi <weiyix.feng@intel.com>"]
license = "BSD"
repository = "https://github.com/projectacrn/acrn-hypervisor"
default-run = "acrn-configurator"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
openssl = "0.10.72" # fix vulnerability only
idna = "=1.0.0"     # fix vulnerability only
url = "=2.5.1"      # fix vulnerability only
tokio = "=1.43.1"   # fix vulnerability only
crossbeam-channel = "=0.5.15"   # fix vulnerability only
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
tauri = { version = "1.6.7", features = ["api-all", "devtools"] }
log = "0.4.17"
glob = "0.3.0"
dirs = "4.0.0"
itertools = "0.10.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
